# Generated by Django 6.0 on 2025-12-09 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('income', models.DecimalField(db_index=True, decimal_places=2, help_text='Plain income (FOR BENCHMARKING ONLY)', max_digits=12)),
            ],
            options={
                'verbose_name': 'Applicant (Baseline)',
                'verbose_name_plural': 'Applicants (Baseline)',
                'db_table': 'applicant_baseline',
            },
        ),
        migrations.CreateModel(
            name='ApplicantEncrypted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('income_ciphertext', models.TextField(help_text='Encrypted income. Range queries require decrypt-all.')),
            ],
            options={
                'verbose_name': 'Applicant (Encrypted Income)',
                'verbose_name_plural': 'Applicants (Encrypted Income)',
                'db_table': 'applicant_encrypted',
            },
        ),
        migrations.CreateModel(
            name='PersonBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ssn', models.CharField(db_index=True, help_text='Plain SSN (FOR BENCHMARKING ONLY - never use in production)', max_length=9)),
            ],
            options={
                'verbose_name': 'Person (Baseline)',
                'verbose_name_plural': 'People (Baseline)',
                'db_table': 'person_baseline',
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='person_base_last_na_4376f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='PersonEncrypted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ssn_ciphertext', models.TextField(help_text='Encrypted SSN (Fernet). Never access directly.')),
                ('ssn_hash', models.CharField(db_index=True, help_text='SHA-256 hash of SSN for equality queries.', max_length=64)),
            ],
            options={
                'verbose_name': 'Person (Encrypted)',
                'verbose_name_plural': 'People (Encrypted)',
                'db_table': 'person_encrypted',
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='person_encr_last_na_c36a3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person_baseline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ssn_app.personbaseline')),
                ('person_encrypted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ssn_app.personencrypted')),
            ],
            options={
                'db_table': 'orders',
                'indexes': [models.Index(fields=['created_at'], name='orders_created_77e2b9_idx')],
            },
        ),
    ]
